### ISSUE TITLE
Facing issue at data source creation and deletion

### ISSUE THREAD

**Issue by subhadande** [microsoft/AzureSearch_JFK_Files#85] opened 2020-03-03 08:06 UTC
Hello,

As per the documentation in "https://github.com/microsoft/AzureSearch_JFK_Files", I have given the required details and ran the code. It created data source,blob container,skill set,synonym map,index,indexer and web site keys also set. After that ran cd frontend,npm install,pm run build:prod.
After installing these i returned to console app and pressed a key then it gave me something went wrong. Now I am trying to run the app from starting on wards by downloading the source code again and modifying the parameters. But it is failing like,
Deleting Data Source, Index, Indexer, Skillset and SynonymMap if they exist...
Something went wrong.  Set 'DebugMode' to true in order to see traces.
Press any key to exit.
Please help me on this asap

**Comment by Careyjmac** [comment] 2020-03-03 21:40
Could you follow the instructions to [set the DebugMode parameter to true](https://github.com/microsoft/AzureSearch_JFK_Files/blob/581461fe56d346b239e670de900507d82dd95794/JfkWebApiSkills/JfkInitializer/Program.cs#L30) so that you can share the exact error output?

Also, its possible it did work as expected after you built the website.  After the content is finished indexing, we output the result of a '*' search query to the console, which spews out a ton of text that may look like something was wrong but it was actually correct.  Did you try actually going to the website after it was created and did you confirmed it wasn't working from there?

**Comment by subhadande** [comment] 2020-03-09 10:31
Thanks for response..
Now I am facing issue while indexing data. Till website deployment I have completed.  Indexer is failing with error "Could not execute skill because web API request failed."
Please help me.

**Comment by Careyjmac** [comment] 2020-03-09 22:40
We suspect this is related to recent changes on our side to upgrade to TLS 1.2.  We are investigating this and will hopefully be able to resolve ti soon.

**Comment by subhadande** [comment] 2020-03-10 12:01
Hello,
Can you please let us know when  issue will be resolved.
Also please let us know what is the function is used in this code like httptrigger, queue trigger etc. We are suspecting there might be some issue in our function app.
The error indexer "Could not execute skill because web API request failed" is failing for the operation "Enrichment.WebApiSkill.#12"

**Comment by Careyjmac** [comment] 2020-03-10 16:02
Should be fixed in #86 However, I was unable to reproduce issues with the Azure Functions as they are defined.  Did you edit them in some way?  You may need to consult [the documentation for custom web api skills](https://docs.microsoft.com/azure/search/cognitive-search-custom-skill-web-api) to make sure the edits conform with the expected format.

**Comment by subhadande** [comment] 2020-03-11 12:46
The issue in skill set is fixed and indexer ran successfully. But I am not able to preview the document and empty screen  on toggle view which is similar to issue #24. I have seen the solution for it but it doesn't work for me.

**Comment by subhadande** [comment] 2020-03-11 13:13
Forget to mention that we have edited skills definition in skill set manually as indexer is failing when running from code. After editing skillset definition ran indexer in portal then it was successful.

**Comment by Careyjmac** [comment] 2020-03-11 15:49
I would look at #64 and see if that is helpful.  If you use your own dataset and make any modifications to the defined resources/outputs/what have you, this demo will not be guaranteed to work, and I wouldn't be able to help you unless I am able to see and debug the changes you made.  I have confirmed that as of my latest check in to master, the demo works as is again with the provided data, and any changes are up to you to debug and resolve using [our documentation](https://docs.microsoft.com/en-us/azure/search/).

**Comment by subhadande** [comment] 2020-03-11 17:21
I am not using my own dataset.  Using the below image store only

      <add key="JFKFilesBlobStorageAccountConnectionString" value="SharedAccessSignature=st=2019-05-02T21%3A30%3A00Z&amp;se=9999-12-21T12%3A00%3A00Z&amp;sp=rl&amp;sv=2018-03-28&amp;sr=c&amp;sig=NmOktoltvmd9gLqHidRuQN06xeSXbCVYIVti5prLdmA%3D;BlobEndpoint=https://azsjfkfiles.blob.core.windows.net/" />
      <add key="JFKFilesBlobContainerName" value="jfkfiles" />

![jfk](https://user-images.githubusercontent.com/58325753/76444957-b34ebb80-63ea-11ea-89b6-5cc6199a231a.PNG)

**Comment by subhadande** [comment] 2020-03-11 17:23
I am not getting any data only file name is displaying in the results tab.

**Comment by subhadande** [comment] 2020-03-12 07:50
Hi when we are trying to call apis as present in skillSet : /api/hoc-generator  or /api/image-store or /api/link-cryptonyms-list... We are getting 404 - Not found error...
Example: https://{azurefunctionuri}/api/image-store? code={azurefunctionhostkey}
When we replace the URI and key values with actual parameters, getting Error 404 not found

Can you please help and let us know why we are not able to call these api from our app. 
Due to which hocr and other elements are not getting generated.. Thus not able to preview the image in app...

**Comment by Careyjmac** [comment] 2020-03-12 15:53
Did you deploy the solution using the provided arm template?  This template should have deployed an Azure Function with the code from this repo that contains those APIs, and then you should have copied in the credentials for that Azure Function instance into your App.config file.  If the arm template deployment failed for some reason or you deleted the Azure Function instance, that would explain why these APIs aren't seemingly able to be found.  My suggestion would be to start deploying the solution from scratch, i.e. delete the resources you deployed previously and follow the instructions given here again, and assuming there is no failure along the way, it should work.

**Comment by subhadande** [comment] 2020-03-13 12:59
We are not using the template provided in this solution. Our policy is restricting us to use this template. So we have used our own template to create function app.

Is it possible for you to provide a template that will deploy Azure function app only? 
Please confirm us that this functionality will work only when we have used the templates provided by you in this solution?

**Comment by Careyjmac** [comment] 2020-03-13 16:36
It is required to have at least deployed the included Azure Function code.  You can do this yourself if for some reason you really can't use the include ARM template, but we included it to make the deployment process as easy and seemless as possible so it really is the recommended way.  Here is some documentation on how you may be able to deploy the Azure Function yourself if you need to: https://tutorials.visualstudio.com/first-azure-function/publish

You'll need to deploy the included "JfkWebApiSkills" project and put the credentials for the Azure Function that you deployed it to in the App.config file in order for the demo to work.  You may also want to take a look at our [power skills repo](https://github.com/Azure-Samples/azure-search-power-skills), the HocrGenerator and the ImageStore skill are duplicates of two of the included functions here, and depending on your use case you can probably just get rid of the Cryptonym skill, or otherwise use [the CustomEntityLookupSkill](https://docs.microsoft.com/azure/search/cognitive-search-skill-custom-entity-lookup) if you really need to.

**Comment by subhadande** [comment] 2020-03-17 15:43
Thanks for the update. I will try and let you know

**Comment by subhadande** [comment] 2020-03-24 09:36
Hi,

As suggested, I have created function app from visual studio. All the 5  function apps created after publishing the function from visual studio.
I have tried to run all the function apps created. But I am getting 404 error for hocr-generator ,link-cryptonyms-list,link-cryptonyms and image-store function apps.
 For facet-graph-nodes I am getting "facet-graph-nodes - Information for the search service is missing Information for the search service is missing".
I have tried to deploy the project but it is failing while creating skill set. I have debugged the code and it is giving 409 response.

Please suggest any help on this

**Comment by Careyjmac** [comment] 2020-03-24 15:30
You need to add a few application settings to the Azure Function so that it can access the search service and blob storage account.  There settings are mentioned in the [local settings here](https://github.com/microsoft/AzureSearch_JFK_Files/blob/master/JfkWebApiSkills/JfkWebApiSkills/local.settings.json), and [here are instructions](https://docs.microsoft.com/en-us/azure/azure-functions/functions-how-to-use-azure-function-app-settings) on how to add them to the deployed function (make sure you use the names as defined in the local settings in order for it to work properly

I apologize, I forgot about this step since [the ARM template does this for you](https://github.com/microsoft/AzureSearch_JFK_Files/blob/5f9cf6c5eb65f1d028cc89973dd14caff38040e5/azuredeploy.json#L201) when you use it to deploy and I haven't done it the manual way you are trying to in a very long time.

**Comment by subhadande** [comment] 2020-03-26 09:41
Hi,

As you suggested, I have configured search service and blob storage details. Now I am getting response from facet-graph-nodes function.
When I tried to deploy the application, it is failing at skillset creation. I have debugged and got to know it is failing in keyhelper.cs file at line number 18. The string formed at this point will be like,
https://<functionappname>.scm.azurewebsites.net/api/functions/admin/masterkey
I have tried to access this url but i am getting error,
"{"Message":"An error has occurred.","ExceptionMessage":"Runtime keys are stored on blob storage. This API doesn't support this configuration. Please change Environment variable AzureWebJobsSecretStorageType value to 'Files'. For more info, visit https://aka.ms/funcsecrets","ExceptionType":"System.InvalidOperationException","StackTrace":"   at Kudu.Core.Functions.FunctionManager.<GetKeyObjectFromFile>d__9`1.MoveNext() in C:\\Kudu Files\\Private\\src\\master\\Kudu.Core\\Functions\\FunctionManager.cs:line 141\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Kudu.Core.Functions.FunctionManager.<GetMasterKeyAsync>d__11.MoveNext() in C:\\Kudu Files\\Private\\src\\master\\Kudu.Core\\Functions\\FunctionManager.cs:line 213\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Kudu.Services.Functions.FunctionController.<GetMasterKey>d__11.MoveNext() in C:\\Kudu Files\\Private\\src\\master\\Kudu.Services\\Functions\\FunctionController.cs:line 121"}"

 In postman , I am getting 409 error while trying to access it.

Please suggest any help on this.

**Comment by Careyjmac** [comment] 2020-03-26 16:35
The point of that helper method was to make it as easy as possible for us to deploy the sample for you using the ARM template.  Did you not put anything into the "AzureFunctionSiteName" field in the App.config file?  You are saying the uri string formed would be missing the site name so it would seem like it is missing.  If its really not an option for you to paste all of the values required into the App.config file for some reason, you may want to add the host key value yourself.  That would need to be everywhere that KeyHelper.GetAzureFunctionHostKey is called.

I really can't stress enough how much better it would be if you could follow the instructions as described in the README file, using the provided template and copying and pasting all of the required secrets into the provided App.config file.  The goal of this sample was to make it as easy as possible for you to deploy, and that means that if you are not following the provided instructions for whatever reason, there could be several gotchas where things won't be configured properly (as you have experienced).  If you really can't use the template or paste all of the secrets for whatever reason, I highly recommend reading through the instructions anyways and stepping through the code yourself as these issues are also fairly debuggable if it comes down to that.

**Comment by subhadande** [comment] 2020-03-26 16:57
I have configured all the required details in app.config file. By mistake I have given like this,
https://.scm.azurewebsites.net/api/functions/admin/masterkey 
But actually the correct url is,
https://<functionsitename>.scm.azurewebsites.net/api/functions/admin/masterkey

I have re-verified README file, but I did not miss any instruction or step.

**Comment by Careyjmac** [comment] 2020-03-27 21:12
Its probably an issue with whatever specific Azure Function instance you deployed based on the error message.  I am unfortunately unfamiliar with that error message so this is probably the end of my ability to try to help.

**Comment by Careyjmac** [comment] 2021-07-08 00:13
Closing due to inactivity

**Closed by Careyjmac** 2021-07-08 00:13 UTC
