### ISSUE TITLE
SearchServices apiKey value does not fall within the expected range

### ISSUE THREAD

**Issue by chiuhc24** [Microsoft/AzureSearch_JFK_Files#51] opened 2018-09-25 06:48 UTC
Trying to setup the jfk files project, however, when I try to execute step 12 (run the JFKInitializer), this error was thrown.

![2018-09-25 14 48 37](https://user-images.githubusercontent.com/37725541/45997419-0b4c1200-c0d2-11e8-92d3-ba767895d27d.png)

**Comment by Sighillrob** [comment] 2018-10-05 02:59
This is an issue with Mac and the Mono runtime with the Azure Service Client its passing a blank sting to the ProductHeaderValue (https://github.com/Azure/azure-sdk-for-net/issues/4651 and https://github.com/mono/mono/issues/10227 )and an update is planned in the near future, the guidance i was given is to build on a Windows machine.

**Comment by gottscj** [comment] 2018-10-11 13:02
@Sighillrob,

Are there currently any workarounds for this?

**Comment by Sighillrob** [comment] 2018-10-11 18:58
Unfortunately, there isn't thus far I have continued updating the beta release and there hasn't been a mononoframework to resolve this.  I decided to build out a VirtualBox windows 10 box and install 2017 VS on that it's working just a bit slow for me.

**Comment by gottscj** [comment] 2018-10-11 19:08
It seems to be fixed on the preview release v5.18.0.143.

Br

**Comment by gottscj** [comment] 2018-10-11 19:10
Oh wait. I apologise. My issue is related to this, but not the same. Please disregard my comment. I have not confirmed this issue is solved

**Comment by Sighillrob** [comment] 2018-10-11 19:19
IM currently installing 5.12.0.309 and iterating up on the stable releases right now.  then jumping back to the beta releases.

**Comment by Sighillrob** [comment] 2018-10-11 19:20
5.16.0.151 is my next test on the Alpha channel

**Comment by aatobaa** [comment] 2018-10-12 03:42
@dsgouda this is related to the issue you closed on https://github.com/Azure/azure-sdk-for-net/issues/4651

**Comment by brjohnstmsft** [comment] 2018-11-13 03:07
Closing this as the issue is tracked elsewhere: https://github.com/Azure/azure-sdk-for-net/issues/4651

**Closed** 2018-11-15 17:39 UTC
